### ISSUE TITLE
flutterにfireaseを追加する

### ISSUE THREAD

**Issue by toshiki31** [spicy-ranking/spicy-ranking#1]

**Comment by akkicoke** [comment]
firebaseを繋げてfirestoreからリアルタイムでデータ取得まで成功

firestore中のコレクションspicy-cup-noodleから一覧取得

Xcodeのビルドげきおそです(約10分)
<img width="401" alt="スクリーンショット 2023-05-28 13 55 35" src="https://github.com/spicy-ranking/spicy-ranking/assets/85013672/951538d6-9e66-4715-aa13-9873d15f2354">
