### ISSUE TITLE
入力ページを作る

### ISSUE THREAD

**Issue by toshiki31** [spicy-ranking/spicy-ranking#2]
アプリケーションの入力ページを作る

![image](https://github.com/spicy-ranking/spicy-ranking/assets/86425759/4f12001a-b66f-4125-8811-5c2ec704871e)

**Comment by toshiki31** [comment]
## やったこと
- 入力ページを実装
![Simulator Screenshot - iPhone SE (3rd generation) - 2023-05-23 at 19 06 30](https://github.com/spicy-ranking/spicy-ranking/assets/86425759/52a7548b-ed9e-49e0-8630-92d46cfb6a23)

## 内容
- main.dartを実行するとInput.dartの内容が表示される(home変数に設定しているから)
- input.dartはAppBarとbody(body.dart)に記述
- body.dartではcomponents内のファイルを組み合わせて記述
## 確認方法
1. VSCode右下の No Deviceをクリック
2. 画面上部で Start ios (みたいなやつをクリック)
3. Simulator(アプリのあいこん)を右クリック
4. Deviceをクリック
5. iPhoneの機種を選択（多分なんでもいい）
6. main.dart をrunさせる（VSCode右上の三角形）
## やってないこと
- プルダウンで表示させている内容DBの内容とくっつける
- 送信ボタンのリクエスト処理
- カレゴリー(input/ranking)を押すと画面遷移させるルーティング

**Comment by akkicoke** [comment]
動作確認OK！
